os: linux

dist: bionic

language: scala

jdk:
  - openjdk8

script:
  - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install
  - ./mill scalatags.js.__.test
  - ./mill scalatags.jvm.__.test
  - ./mill scalatags.native.__.compile

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.mill
    - $HOME/.coursier
    - $HOME/.cache/coursier/v1
